xml = spine_mc.xml
data = spine_data.xml
tag = spine
output = run2
chi2 = PROCNP
verbosity = 2
nthread = 8
scale-by-width = true
label = SPINE

[profile]
spline-order = GENIEReWeight_SBNNuSyst_GENIE_multisigma_FracPN_CCMEC GENIEReWeight_SBNNuSyst_GENIE_multisigma_XSecShape_CCMEC GENIEReWeight_SBN_v1_multisigma_CoulombCCQE GENIEReWeight_SBN_v1_multisigma_DecayAngMEC GENIEReWeight_SBN_v1_multisigma_FrCEx_N GENIEReWeight_SBN_v1_multisigma_FrCEx_pi GENIEReWeight_SBN_v1_multisigma_MaCCRES GENIEReWeight_SBN_v1_multisigma_MvCCRES GENIEReWeight_SBN_v1_multisigma_NormCCMEC GENIEReWeight_SBN_v1_multisigma_RPA_CCQE ZExpPCAWeighter_SBNNuSyst_ZExpPCA_multisigma_b1 ZExpPCAWeighter_SBNNuSyst_ZExpPCA_multisigma_b2 ZExpPCAWeighter_SBNNuSyst_ZExpPCA_multisigma_b3 ZExpPCAWeighter_SBNNuSyst_ZExpPCA_multisigma_b4 var01 var04 var11 var13 var05 var06 var12 var10 var07 nu_ICARUS:0.01 nu_ICARUS_numu_n:0.02
